version: '3.8'

services:
  app:
    image: ${APP_IMAGE}
    restart: unless-stopped
    expose:
      - "${APP_PORT}"

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
      - APP_PORT=${APP_PORT}

volumes:
  caddy_data:
  caddy_config:

