
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./monitoring/Caddyfile:/etc/caddy/monitoring/Caddyfile

    env_file:
      - .env
    networks:
         - caddy_net 
volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net: 
       external: true
